242479753: Fix a syntax error in test input
Also, add a test that showcases false positives of VersionChecks,
which was found while trying a compiler's suggestion for that syntax
error: COMMA_IN_WHEN_CONDITION_WITHOUT_ARGUMENT

Bug: 242479753
Test: existing one fixed, new unit test added
Change-Id: Iba81626df9bac934a41c75a535b651086e9ae90d