Fix NoClassDefFoundError with Gradle 4.3 or earlier (again).
This bug was fixed in commit 91978236f75d4f1490bc8b5af9e8a146b9dda6e1,
but reappeared after commit f71cc26a8cda8bf0fcc2bc3f2335be6186651071:
AppPlugin references the new ModelBuilder, making build or sync fail
on older Gradle versions before the plugin can run a version check to
provide a message asking users to update their Gradle version.

This fix slightly decreases code design, but hopefully it's still
acceptable.

Fixes: 73383831
Test: New GradleVersionCheckTest
Change-Id: Ic625489c6121921a6a850f546afaa217a8afc1a0