71364472: Add missing extension point in Kotlin setup
This CL fixes a crash from lint observed on a user project:
java.lang.IllegalArgumentException: Missing extension point: org.jetbrains.kotlin.diagnosticSuppressor in area null
IllegalArgumentException:ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:339)←ExtensionsAreaImpl.getExtensionPoint(ExtensionsAreaImpl.java:347)

The root cause was that our manual registration of the Kotlin
environment was missing the diagnostic suppressor extension
point (which is not normally used, but something in the given
user project is triggering it).

Also fixes misleading error messages in the obsolete lint check
rule warnings observed in that project.

Test: Included
Change-Id: Ic76c1d43ce2b5b97cad02cbe3f3896fd06a0b37b